version: '3.3'
services:
  postgres_db:
    image: postgres:latest
    container_name: PostgresCont 
    restart: always
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres123
    ports:
    - '5432:5432'
    volumes:
    - ../pg_data:/var/lib/postgresql/data
volumes:
  postgres_db:
    driver: local
