version: '3.3'
services:
  postgres_db:
    image: postgres:9.6
    container_name: DB_Postgres
    restart: always
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres123
    ports:
    - '8081:5432'
    volumes:
    - /etc/pg_data:/var/lib/postgresql/data
  app:
    build: .
    container_name: API_FaceRecognition
    ports:
    - '8000:8000'
    depends_on:
    - postgres_db
    volumes:
    - /etc/mydata:/app/app/data
volumes:
  postgres_db:
    driver: local